# settings.py

# --- Внутреннее разрешение (пиксель-арт) ---
WIDTH, HEIGHT = 320, 240
SCALE = 3  # окно будет 960x720

# --- ЦВЕТА ---
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
AUTUMN_YELLOW = (204, 153, 51)

# --- ТАЙМИНГИ ПЕРЕХОДОВ ---
BLACK_DURATION = 400   
FADEIN_DURATION = 1000

# --- СОСТОЯНИЯ ИГРЫ ---
STATE_TITLE      = "TITLE"
STATE_TITLE_2    = "TITLE_2"       
STATE_MAIN_MENU  = "MAIN_MENU" 
STATE_STORY      = "STORY"
STATE_GAME       = "GAME"
STATE_DOOR       = "DOOR"
STATE_TRANSITION = "TRANSITION"

STATE_ATRIUM       = "ATRIUM"
STATE_GUARD_CHOICE = "GUARD_CHOICE"
STATE_GUARD_DIALOG = "GUARD_DIALOG"
STATE_GUARD_FIRST  = "GUARD_FIRST"
STATE_GUARD_POST_BAHA = "GUARD_POST_BAHA"

STATE_CORIDOR             = "CORIDOR"
STATE_CORIDOR_DOOR        = "CORIDOR_DOOR"
STATE_CORIDOR_BAHA_DIALOG = "CORIDOR_BAHA_DIALOG"
STATE_CORIDOR_BAHA_RUN    = "CORIDOR_BAHA_RUN"
STATE_BAHA_EVENT          = "BAHA_EVENT"

STATE_LADDER      = "LADDER"
STATE_LADDER_DOOR = "LADDER_DOOR"

STATE_CORIDOR2FLOOR       = "CORIDOR2FLOOR"
STATE_CORIDOR2FLOOR_DOOR  = "CORIDOR2FLOOR_DOOR" 
STATE_LOCKERS_DIALOG      = "LOCKERS_DIALOG"         
STATE_SPECIAL_LOCKER_DIALOG = "SPECIAL_LOCKER_DIALOG"

STATE_CABINET       = "CABINET"
STATE_CABINET_DOOR  = "CABINET_DOOR"
STATE_CORIDORFINAL  = "CORIDORFINAL" 

STATE_SAVE_MENU = "SAVE_MENU"
STATE_OFFICE    = "OFFICE"
STATE_PAKETT_DIALOG       = "PAKETT_DIALOG"
STATE_SPECIFICCOMP_DIALOG = "SPECIFICCOMP_DIALOG"

# Новые состояния для ивента с Бахой в офисе:
STATE_OFFICE_BAHA_EVENT_START = "OFFICE_BAHA_EVENT_START"
STATE_OFFICE_BAHA_DIALOG_1    = "OFFICE_BAHA_DIALOG_1"
STATE_OFFICE_BAHA_WALK        = "OFFICE_BAHA_WALK"
STATE_OFFICE_BAHA_DIALOG_2    = "OFFICE_BAHA_DIALOG_2"
STATE_OFFICE_BAHA_FLASH       = "OFFICE_BAHA_FLASH"
STATE_BATTLE                  = "BATTLE"

STATE_GAMEOVER_ANIM   = "GAMEOVER_ANIM"
STATE_GAMEOVER_SCREEN = "GAMEOVER_SCREEN"

# --- КООРДИНАТЫ ПОЯВЛЕНИЯ (СПАВНЫ) ---
# --- КООРДИНАТЫ ПОЯВЛЕНИЯ (СПАВНЫ) ---
# Спавны в Атриуме (куда мы попадаем с улицы)
SPAWN_ATRIUM_1_X = 728
SPAWN_ATRIUM_1_Y = 626
SPAWN_ATRIUM_2_X = 226   # <-- Настройте X для второй двери в Атриуме
SPAWN_ATRIUM_2_Y = 626  # <-- Настройте Y для второй двери в Атриуме

# Спавны в Коридоре (куда мы попадаем из Атриума)
SPAWN_CORIDOR_1_X = 737 
SPAWN_CORIDOR_1_Y = 624 
SPAWN_CORIDOR_2_X = 247  # <-- Настройте X для второй двери в коридоре
SPAWN_CORIDOR_2_Y = 624  # <-- Настройте Y для второй двери в коридоре

SPAWN_LADDER_X = 753
SPAWN_LADDER_Y = 560
SPAWN_CORIDOR2FLOOR_X = 52
SPAWN_CORIDOR2FLOOR_Y = 590
SPAWN_CORIDORFINAL_X = 764
SPAWN_CORIDORFINAL_Y = 528
SPAWN_OFFICE_X = 790
SPAWN_OFFICE_Y = 494
SPAWN_SAVE_CONTINUE_X = 210
SPAWN_SAVE_CONTINUE_Y = 602